StartupEvents.registry('item', event => {
    event.create('talpanas').displayName('Talpanas Picture');
    event.create('grottoceratops').displayName('Grottoceratops Picture');
    event.create('atlatitan').displayName('Atlatitan Picture');
    event.create('laviathan').displayName('Laviathan Picture');
    event.create('froststalker').displayName('Froststalker Picture');
    event.create('majungasaurus').displayName('Majungasaurus Picture');
    event.create('tyrannosaurus_rex').displayName('Tyrannosaurus Rex Picture');
    event.create('velociraptor').displayName('Velociraptor Picture');
    event.create('austroraptor').displayName('Austroraptor Picture');
    event.create('ulughbegsaurus').displayName('Ulughbegsaurus Picture');
    event.create('hwachavenator').displayName('Hwachavenator Picture');
    event.create('subterranodon').displayName('Subterranodon Picture');
    event.create('vallumraptor').displayName('Vallumraptor Picture');
    event.create('tremorsaurus').displayName('Tremorsaurus Picture');
    event.create('brachiosaurus').displayName('Brachiosaurus Picture');
    event.create('triceratops').displayName('Triceratops Picture');
    event.create('kentrosaurus').displayName('Kentrosaurus Picture');
    event.create('antarctopelta').displayName('Antarctopelta Picture');
    event.create('cotylorhynchus').displayName('Cotylorhynchus Picture');
    event.create('sniffer').displayName('Sniffer Picture');
    event.create('pachycephalosaurus').displayName('Pachycephalosaurus Picture');
    event.create('relicheirus').displayName('Relicheirus Picture');
    event.create('smilodon').displayName('Smilodon Picture');
    event.create('megalania').displayName('Megalania Picture');
    event.create('barinasuchus').displayName('Barinasuchus Picture');
    event.create('stethacanthus').displayName('Stethacanthus Picture');
    event.create('palaeophis').displayName('Palaeophis Picture');
    event.create('dunkleosteus').displayName('Dunkleosteus Picture');
    event.create('anurognathus').displayName('Anurognathus Picture');
    event.create('ammonite').displayName('Ammonite Picture');
    event.create('scaumencia').displayName('Scaumencia Picture');
    event.create('tusklin').displayName('Tusklin Picture');
    event.create('trilocaris').displayName('Trilocaris Picture');
    event.create('mammoth').displayName('Mammoth Picture');
    event.create('megatherium').displayName('Megatherium Picture');
    event.create('paraceratherium').displayName('Paraceratherium Picture');
    event.create('beelzebufo').displayName('Beelzebufo Picture');
    event.create('eryon').displayName('Eryon Picture');
    event.create('gigantopithicus').displayName('Gigantopithicus Picture');
    event.create('talapanas').displayName('Talapanas Picture');
    event.create('rocky_roller').displayName('Rocky Roller Picture');
    event.create('dawn_horse').displayName('Dawn Horse Picture');
    event.create('doedicurus').displayName('Doedicurus Picture');
    event.create('eolactoria').displayName('Eolactoria Picture');
    event.create('apthoroblattina').displayName('Apthoroblattina Picture');
    event.create('leptictidium').displayName('Leptictidium Picture');
    event.create('borealopelta').displayName('Borealopelta Picture');
    event.create('falcatus').displayName('Falcatus Picture');
    event.create('slovenicus').displayName('Slovenicus Picture');
    event.create('blochius').displayName('Blochius Picture');
    event.create('neilpeartia').displayName('Neilpeartia Picture');
    event.create('tapejara').displayName('Tapejara Picture');
    event.create('giganhinga').displayName('Giganhinga Picture');
    })
